In [43]:
import pandas as pd

In [44]:
df = pd.read_csv('../data/challenge_62.csv')

df.head()

,Installation Date,DeviceID,EventName,IDFA,EventFireDate
0,11/28/2015 17:57,2,Offer - Use at Location,1,11/30/2015 3:17:04
1,11/28/2015 17:57,2,Offer - Use at Location,1,12/6/2015 17:22:00
2,11/28/2015 17:57,2,Offer - Use at Location,1,12/6/2015 17:22:02
3,11/28/2015 17:57,2,Offer - Use at Location,1,1/30/2016 6:34:19
4,11/28/2015 17:57,2,Offer - Use at Location,1,1/30/2016 6:34:25

In [45]:
# convert string to datetime, sort df

df['EventFireDate'] = pd.to_datetime(df['EventFireDate'], format='%m/%d/%Y %H:%M:%S')
df = df.sort_values(['DeviceID', 'IDFA', 'EventFireDate']).reset_index(drop=True)

df.head()

,Installation Date,DeviceID,EventName,IDFA,EventFireDate
0,11/28/2015 17:57,2,Offer - Use at Location,1,2015-11-30 03:17:04
1,11/28/2015 17:57,2,Offer - Use at Location,1,2015-12-06 17:22:00
2,11/28/2015 17:57,2,Offer - Use at Location,1,2015-12-06 17:22:02
3,11/28/2015 17:57,2,Offer - Use at Location,1,2016-01-30 06:34:19
4,11/28/2015 17:57,2,Offer - Use at Location,1,2016-01-30 06:34:25

In [46]:
# identify duplicate clicks

df.loc[0, 'DuplicateClick'] = False

for i in range(1, len(df)):
    if (df.loc[i, 'DeviceID'] == df.loc[i-1, 'DeviceID']) and (df.loc[i, 'IDFA'] == df.loc[i-1, 'IDFA']):
        df.loc[i, 'DuplicateClick'] = (df.loc[i, 'EventFireDate'] - df.loc[i-1, 'EventFireDate']).total_seconds() <= 30
    else:
        df.loc[i, 'DuplicateClick'] = False

df

,Installation Date,DeviceID,EventName,IDFA,EventFireDate,DuplicateClick
0,11/28/2015 17:57,2,Offer - Use at Location,1,2015-11-30 03:17:04,False
1,11/28/2015 17:57,2,Offer - Use at Location,1,2015-12-06 17:22:00,False
2,11/28/2015 17:57,2,Offer - Use at Location,1,2015-12-06 17:22:02,True
3,11/28/2015 17:57,2,Offer - Use at Location,1,2016-01-30 06:34:19,False
4,11/28/2015 17:57,2,Offer - Use at Location,1,2016-01-30 06:34:25,True
5,11/28/2015 17:57,2,Offer - Use at Location,1,2016-01-30 06:34:32,True
6,11/28/2015 17:57,2,Offer - Use at Location,1,2016-02-10 23:59:50,False
7,11/28/2015 17:57,2,Offer - Use at Location,1,2016-02-11 00:00:16,True
8,10/17/2015 17:57,3,Offer - Use at Location,2,2015-10-18 03:17:04,False
9,10/17/2015 17:57,3,Offer - Use at Location,2,2015-11-06 17:22:00,False
10,10/17/2015 17:57,3,Offer - Use at Location,2,2015-11-06 17:22:02,True
11,10/17/2015 17:57,3,Offer - Use at Location,2,2016-12-30 06:34:19,False
12,10/17/2015 17:57,3,Offer - Use at Location,2,2016-12-30 06:34:25,True
13,12/29/2015 17:57,4,Offer - Use at Location,3,2016-12-30 06:34:32,False
14,12/29/2015 17:57,4,Offer - Use at Location,3,2016-12-31 23:59:50,False
15,12/29/2015 17:57,4,Offer - Use at Location,3,2017-01-01 00:00:16,True