In [162]:
import pandas as pd
from datetime import datetime

In [163]:
input_df = pd.read_csv('../data/challenge_126.csv')
input_df['datetime_finished'] = pd.to_datetime(input_df['datetime_finished'])

input_df.head()

  datetime_finished country_name  passed_exams
0        2018-02-26    Argentina             1
1        2018-07-03    Argentina             1
2        2017-10-16    Australia             1
3        2017-11-01    Australia             1
4        2017-11-04    Australia             1

In [164]:
# create df of all dates in time range

dates = pd.date_range(start='2017-10-01', end=datetime.now())
dates_df = pd.DataFrame(dates, columns=['date'])

dates_df.head()

        date
0 2017-10-01
1 2017-10-02
2 2017-10-03
3 2017-10-04
4 2017-10-05

In [165]:
# create df of all countries in the data

countries = input_df['country_name'].unique()
countries_df = pd.DataFrame(countries, columns=['country'])

countries_df.head()

     country
0  Argentina
1  Australia
2     Brazil
3     Canada

In [166]:
# cross join dates and countries dfs

scaffolded_df = pd.merge(dates_df, countries_df, how='cross')

scaffolded_df.head()

        date    country
0 2017-10-01  Argentina
1 2017-10-01  Australia
2 2017-10-01     Brazil
3 2017-10-01     Canada
4 2017-10-02  Argentina

In [167]:
# join main data with scaffolded dates

df = pd.merge(scaffolded_df, input_df, how='left', left_on=['date', 'country'], right_on=['datetime_finished', 'country_name'])[['date', 'country', 'passed_exams']].sort_values(['country', 'date']).reset_index(drop=True)
df['passed_exams'] = df['passed_exams'].fillna(0)


df.head()

        date    country  passed_exams
0 2017-10-01  Argentina           0.0
1 2017-10-02  Argentina           0.0
2 2017-10-03  Argentina           0.0
3 2017-10-04  Argentina           0.0
4 2017-10-05  Argentina           0.0

In [ ]:
# calculate running total

df['running total'] = 0

for i in range(len(df)):
    if i == 0:
        df.loc[i, 'running total'] = df.loc[i, 'passed_exams']
    elif df.loc[i, 'country'] == df.loc[i-1, 'country']:
        df.loc[i, 'running total'] = df.loc[i-1, 'running total'] + df.loc[i, 'passed_exams']

df.head()

        date    country  passed_exams  running total
0 2017-10-01  Argentina           0.0              0
1 2017-10-02  Argentina           0.0              0
2 2017-10-03  Argentina           0.0              0
3 2017-10-04  Argentina           0.0              0
4 2017-10-05  Argentina           0.0              0