In [41]:
import pandas as pd
import re

In [42]:
df = pd.read_csv('../data/challenge_2.csv')

df

                                             Field_1
0  "Mary had a little lamb whose fleece was white...
1  "I do not like green eggs and ham",456,'25-DEC...

In [43]:
# parse out fields and convert string to date

df['poem'] = df['Field_1'].apply(lambda x: re.search('"(.+?)",(.+?),.(.+?).$', x).group(1))
df['poem_id'] = df['Field_1'].apply(lambda x: re.search('"(.+?)",(.+?),.(.+?).$', x).group(2))
df['date'] = df['Field_1'].apply(lambda x: re.search('"(.+?)",(.+?),.(.+?).$', x).group(3))

df['date'] = pd.to_datetime(df['date'], format='%d-%b-%y')

df

,Field_1,poem,poem_id,date
0,"""Mary had a little lamb whose fleece was white...",Mary had a little lamb whose fleece was white ...,123,2001-06-16
1,"""I do not like green eggs and ham"",456,'25-DEC...",I do not like green eggs and ham,456,2010-12-25